"""empty message

Revision ID: 188eabcbde6c
Revises: 
Create Date: 2021-09-20 17:33:09.479235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188eabcbde6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bus_reg_nbr', sa.String(length=20), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('mobile_phone', sa.String(length=20), nullable=False),
    sa.Column('position_title', sa.String(length=50), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Client_Contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position_title', sa.String(length=50), nullable=True),
    sa.Column('address_1', sa.String(length=100), nullable=True),
    sa.Column('address_2', sa.String(length=100), nullable=True),
    sa.Column('address_3', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('post_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_contact_id', sa.Integer(), nullable=False),
    sa.Column('consulant_id', sa.Integer(), nullable=False),
    sa.Column('client_manager_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_from_date', sa.Date(), nullable=False),
    sa.Column('report_to_date', sa.Date(), nullable=True),
    sa.Column('engagement_reference', sa.String(length=20), nullable=False),
    sa.Column('report_status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['client_contact_id'], ['Client_Contacts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ),
    sa.ForeignKeyConstraint(['client_manager_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['consulant_id'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Report_Items',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('report_item_nbr', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_sequence_nbr', sa.Integer(), nullable=False),
    sa.Column('item_description', sa.String(), nullable=False),
    sa.Column('item_complete', sa.Boolean(), nullable=True),
    sa.Column('request_expected_outcome', sa.String(), nullable=True),
    sa.Column('issue_status', sa.String(length=20), nullable=True),
    sa.Column('issue_action_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['Reports.id'], ),
    sa.PrimaryKeyConstraint('report_id', 'report_item_nbr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Report_Items')
    op.drop_table('Reports')
    op.drop_table('Client_Contacts')
    op.drop_table('Contacts')
    op.drop_table('Clients')
    # ### end Alembic commands ###
